packages:
  - "packages/*"
  - "apps/inheritance-case-management/api"
  - "apps/inheritance-case-management/web"
  - "apps/inheritance-tax-app"
  - "apps/retirement-tax-calc"
  - "apps/gift-tax-simulator"
  - "apps/gift-tax-docs"
  - "apps/inheritance-tax-docs"
  - "apps/shares-valuation"
  - "apps/medical-stock-valuation"
  - "apps/Required-documents-for-tax-return/frontend"
  - "apps/Required-documents-for-tax-return/backend"
