server {
    listen 80;
    server_name localhost;
    absolute_redirect off;

    location /used-asset-life {
        alias /usr/share/nginx/html/used-asset-life;
        try_files $uri $uri/ /used-asset-life/index.html;
    }

    location /used-asset-life/assets {
        alias /usr/share/nginx/html/used-asset-life/assets;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
