import type { FamilyMember, Policy, Agency } from '@/types';

export function getSampleFamilyMembers(): FamilyMember[] {
  return [
    { id: 'm1', name: '佐々木健介', nameKana: 'ササキケンスケ', relationship: '本人', birthDate: '1966-08-04', gender: 'male' },
    { id: 'm2', name: '北斗晶', nameKana: 'ホクトアキラ', relationship: '配偶者', birthDate: '1985-04-12', gender: 'female' },
    { id: 'm3', name: '佐々木誠也', nameKana: 'ササキセイヤ', relationship: '長男', birthDate: '2004-11-06', gender: 'male' },
    { id: 'm4', name: '佐々木凛', nameKana: 'ササキリン', relationship: '長女', birthDate: '2008-03-18', gender: 'female' },
  ];
}

export function getSampleAgency(): Agency {
  return {
    name: '新日本プロレス',
    representative: '橋本 信也',
    phone: '050-3317-0226',
  };
}

export function getSamplePolicies(): Policy[] {
  return [
    {
      id: '1',
      companyName: '住友生命',
      policyType: '個人年金保険',
      policyNumber: '-',
      contractDate: '2016-08-01',
      contractAge: 50,
      insuredId: 'm1',
      beneficiaryId: 'm2',
      deathBenefitDisease: 0,
      deathBenefitAccident: 0,
      hospDayDisease: 0,
      hospDayAccident: 0,
      diagnosisBenefit: 0,
      policyEndAge: 85,
      paymentFrequency: 'monthly',
      premiumAmount: 20000,
      paymentEndAge: 65,
      annualPremium: 240000,
      maturityBenefit: 5000000,
    },
    {
      id: '2',
      companyName: 'プルデンシャル生命',
      policyType: '収入保障保険',
      policyNumber: '2709300566',
      contractDate: '2014-04-25',
      contractAge: 48,
      insuredId: 'm1',
      beneficiaryId: 'm2',
      deathBenefitDisease: 60000,
      deathBenefitAccident: 0,
      hospDayDisease: 0,
      hospDayAccident: 0,
      diagnosisBenefit: 0,
      policyEndAge: 70,
      paymentFrequency: 'monthly',
      premiumAmount: 14225,
      paymentEndAge: 70,
      annualPremium: 170700,
      maturityBenefit: 0,
    },
    {
      id: '3',
      companyName: 'プルデンシャル生命',
      policyType: '変額終身保険',
      policyNumber: '2709300558',
      contractDate: '2014-05-01',
      contractAge: 48,
      insuredId: 'm1',
      beneficiaryId: 'm2',
      deathBenefitDisease: 5000000,
      deathBenefitAccident: 5000000,
      hospDayDisease: 0,
      hospDayAccident: 0,
      diagnosisBenefit: 0,
      policyEndAge: 999,
      paymentFrequency: 'monthly',
      premiumAmount: 8935,
      paymentEndAge: 75,
      annualPremium: 107220,
      maturityBenefit: 0,
    },
    {
      id: '4',
      companyName: 'プルデンシャル生命',
      policyType: '医療保険',
      policyNumber: '2709300574',
      contractDate: '2014-04-25',
      contractAge: 48,
      insuredId: 'm1',
      beneficiaryId: 'm2',
      deathBenefitDisease: 0,
      deathBenefitAccident: 0,
      hospDayDisease: 10000,
      hospDayAccident: 10000,
      diagnosisBenefit: 500000,
      policyEndAge: 80,
      paymentFrequency: 'monthly',
      premiumAmount: 10798,
      paymentEndAge: 70,
      annualPremium: 129576,
      maturityBenefit: 0,
    },
    {
      id: '5',
      companyName: 'アフラック生命',
      policyType: 'がん保険',
      policyNumber: 'AFL-2020-001',
      contractDate: '2018-09-01',
      contractAge: 52,
      insuredId: 'm1',
      beneficiaryId: 'm2',
      deathBenefitDisease: 0,
      deathBenefitAccident: 0,
      hospDayDisease: 5000,
      hospDayAccident: 5000,
      diagnosisBenefit: 1000000,
      policyEndAge: 999,
      paymentFrequency: 'monthly',
      premiumAmount: 6200,
      paymentEndAge: 70,
      annualPremium: 74400,
      maturityBenefit: 0,
    },
    {
      id: '6',
      companyName: '東京海上日動あんしん生命',
      policyType: '定期保険',
      policyNumber: 'TMN-2019-015',
      contractDate: '2019-06-15',
      contractAge: 53,
      insuredId: 'm1',
      beneficiaryId: 'm2',
      deathBenefitDisease: 10000000,
      deathBenefitAccident: 10000000,
      hospDayDisease: 0,
      hospDayAccident: 0,
      diagnosisBenefit: 0,
      policyEndAge: 65,
      paymentFrequency: 'monthly',
      premiumAmount: 4500,
      paymentEndAge: 65,
      annualPremium: 54000,
      maturityBenefit: 0,
    },
    {
      id: '7',
      companyName: 'オリックス生命',
      policyType: '終身保険',
      policyNumber: 'ORX-2017-008',
      contractDate: '2017-02-01',
      contractAge: 51,
      insuredId: 'm2',
      beneficiaryId: 'm1',
      deathBenefitDisease: 3000000,
      deathBenefitAccident: 3000000,
      hospDayDisease: 0,
      hospDayAccident: 0,
      diagnosisBenefit: 0,
      policyEndAge: 999,
      paymentFrequency: 'annual',
      premiumAmount: 96000,
      paymentEndAge: 65,
      annualPremium: 96000,
      maturityBenefit: 0,
    },
    {
      id: '8',
      companyName: '明治安田生命',
      policyType: '養老保険',
      policyNumber: 'MY-2021-033',
      contractDate: '2021-04-01',
      contractAge: 16,
      insuredId: 'm3',
      beneficiaryId: 'm1',
      deathBenefitDisease: 2000000,
      deathBenefitAccident: 2000000,
      hospDayDisease: 0,
      hospDayAccident: 0,
      diagnosisBenefit: 0,
      policyEndAge: 30,
      paymentFrequency: 'monthly',
      premiumAmount: 8200,
      paymentEndAge: 30,
      annualPremium: 98400,
      maturityBenefit: 2000000,
    },
    {
      id: '9',
      companyName: 'ソニー生命',
      policyType: '収入保障保険',
      policyNumber: 'SNY-2022-041',
      contractDate: '2022-10-01',
      contractAge: 37,
      insuredId: 'm2',
      beneficiaryId: 'm3',
      deathBenefitDisease: 100000,
      deathBenefitAccident: 0,
      hospDayDisease: 0,
      hospDayAccident: 0,
      diagnosisBenefit: 0,
      policyEndAge: 60,
      paymentFrequency: 'monthly',
      premiumAmount: 3900,
      paymentEndAge: 60,
      annualPremium: 46800,
      maturityBenefit: 0,
    },
  ];
}
