-- Django 版（apps/bank-analyzer-django）が作った表そのもの。
--
-- 2026-10-07 に稼働中の DB から `pg_dump -s --no-owner --no-privileges -t 'analyzer_*'`
-- で取り出したものを、コメントと SET 文だけ落として写した。手を入れていない。
--
-- 新しい DB ではこのまま流れて同じ表ができる。Django 版の DB（表が既にある）へ
-- つなぐときは、流さずに適用済みとして記録する:
--   npx prisma migrate resolve --applied 20261007000000_django_baseline
-- 既定値と削除の連鎖は次のマイグレーションで足す（ここは Django のまま保つ）。

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;

CREATE TABLE public.analyzer_account (
    id bigint NOT NULL,
    account_number character varying(255) NOT NULL,
    bank_name character varying(255),
    branch_name character varying(255),
    account_type character varying(50),
    holder character varying(255),
    case_id bigint NOT NULL,
    passbook_balance integer,
    certificate_balance integer,
    has_accrued_interest boolean NOT NULL,
    passbook_years jsonb NOT NULL,
    inventory_remarks text NOT NULL,
    print_order integer NOT NULL
);

ALTER TABLE public.analyzer_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analyzer_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.analyzer_case (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    custom_patterns jsonb NOT NULL,
    reference_date date
);

ALTER TABLE public.analyzer_case ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analyzer_case_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.analyzer_classificationchange (
    id bigint NOT NULL,
    transaction_identifier bigint NOT NULL,
    transaction_description character varying(255) NOT NULL,
    old_category character varying(100) NOT NULL,
    new_category character varying(100) NOT NULL,
    change_group uuid NOT NULL,
    source character varying(50) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    reverted_at timestamp with time zone,
    case_id bigint NOT NULL,
    transaction_id bigint,
    CONSTRAINT analyzer_classificationchange_transaction_identifier_check CHECK ((transaction_identifier >= 0))
);

ALTER TABLE public.analyzer_classificationchange ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analyzer_classificationchange_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.analyzer_deletionbackup (
    id bigint NOT NULL,
    start_id bigint NOT NULL,
    end_id bigint NOT NULL,
    transaction_data jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    restored_at timestamp with time zone,
    case_id bigint NOT NULL,
    CONSTRAINT analyzer_deletionbackup_end_id_check CHECK ((end_id >= 0)),
    CONSTRAINT analyzer_deletionbackup_start_id_check CHECK ((start_id >= 0))
);

ALTER TABLE public.analyzer_deletionbackup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analyzer_deletionbackup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.analyzer_transaction (
    id bigint NOT NULL,
    date date,
    description character varying(255),
    amount_out integer NOT NULL,
    amount_in integer NOT NULL,
    balance integer,
    is_large boolean NOT NULL,
    is_transfer boolean NOT NULL,
    transfer_to character varying(255),
    category character varying(100) NOT NULL,
    case_id bigint NOT NULL,
    is_flagged boolean NOT NULL,
    memo text,
    classification_score integer NOT NULL,
    account_id bigint,
    description_search text NOT NULL
);

ALTER TABLE public.analyzer_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.analyzer_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.analyzer_account
    ADD CONSTRAINT analyzer_account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.analyzer_case
    ADD CONSTRAINT analyzer_case_name_key UNIQUE (name);

ALTER TABLE ONLY public.analyzer_case
    ADD CONSTRAINT analyzer_case_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.analyzer_classificationchange
    ADD CONSTRAINT analyzer_classificationchange_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.analyzer_deletionbackup
    ADD CONSTRAINT analyzer_deletionbackup_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.analyzer_transaction
    ADD CONSTRAINT analyzer_transaction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.analyzer_account
    ADD CONSTRAINT unique_case_account UNIQUE (case_id, account_number);

CREATE INDEX analyzer_account_case_id_eeba72e1 ON public.analyzer_account USING btree (case_id);

CREATE INDEX analyzer_case_name_2f00419f_like ON public.analyzer_case USING btree (name varchar_pattern_ops);

CREATE INDEX analyzer_cl_case_id_18f699_idx ON public.analyzer_classificationchange USING btree (case_id, created_at);

CREATE INDEX analyzer_cl_case_id_855c2c_idx ON public.analyzer_classificationchange USING btree (case_id, reverted_at);

CREATE INDEX analyzer_classificationchange_case_id_521737b8 ON public.analyzer_classificationchange USING btree (case_id);

CREATE INDEX analyzer_classificationchange_change_group_5b2b2622 ON public.analyzer_classificationchange USING btree (change_group);

CREATE INDEX analyzer_classificationchange_transaction_id_6a4f7c8a ON public.analyzer_classificationchange USING btree (transaction_id);

CREATE INDEX analyzer_deletionbackup_case_id_43d64ad8 ON public.analyzer_deletionbackup USING btree (case_id);

CREATE INDEX analyzer_tr_case_id_0b746a_idx ON public.analyzer_transaction USING btree (case_id, is_transfer);

CREATE INDEX analyzer_tr_case_id_4d6dc2_idx ON public.analyzer_transaction USING btree (case_id, is_large);

CREATE INDEX analyzer_tr_case_id_96ba3a_idx ON public.analyzer_transaction USING btree (case_id, category);

CREATE INDEX analyzer_tr_case_id_ca6c16_idx ON public.analyzer_transaction USING btree (case_id, is_flagged);

CREATE INDEX analyzer_tr_case_id_cfc7bb_idx ON public.analyzer_transaction USING btree (case_id, account_id);

CREATE INDEX analyzer_tr_case_id_ff6ea7_idx ON public.analyzer_transaction USING btree (case_id, date);

CREATE INDEX analyzer_tr_categor_07dd04_idx ON public.analyzer_transaction USING btree (category);

CREATE INDEX analyzer_transaction_account_id_new_4de071e4 ON public.analyzer_transaction USING btree (account_id);

CREATE INDEX analyzer_transaction_case_id_c94f6f84 ON public.analyzer_transaction USING btree (case_id);

CREATE INDEX analyzer_tx_desc_trgm ON public.analyzer_transaction USING gin (description_search public.gin_trgm_ops);

ALTER TABLE ONLY public.analyzer_account
    ADD CONSTRAINT analyzer_account_case_id_eeba72e1_fk_analyzer_case_id FOREIGN KEY (case_id) REFERENCES public.analyzer_case(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.analyzer_classificationchange
    ADD CONSTRAINT analyzer_classificat_case_id_521737b8_fk_analyzer_ FOREIGN KEY (case_id) REFERENCES public.analyzer_case(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.analyzer_classificationchange
    ADD CONSTRAINT analyzer_classificat_transaction_id_6a4f7c8a_fk_analyzer_ FOREIGN KEY (transaction_id) REFERENCES public.analyzer_transaction(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.analyzer_deletionbackup
    ADD CONSTRAINT analyzer_deletionbackup_case_id_43d64ad8_fk_analyzer_case_id FOREIGN KEY (case_id) REFERENCES public.analyzer_case(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.analyzer_transaction
    ADD CONSTRAINT analyzer_transaction_account_id_2bfe6161_fk_analyzer_account_id FOREIGN KEY (account_id) REFERENCES public.analyzer_account(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.analyzer_transaction
    ADD CONSTRAINT analyzer_transaction_case_id_c94f6f84_fk_analyzer_case_id FOREIGN KEY (case_id) REFERENCES public.analyzer_case(id) DEFERRABLE INITIALLY DEFERRED;

