const {chromium}=require('/tmp/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
(async()=>{
 fs.mkdirSync('/work/qa',{recursive:true});
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1100},locale:'ja-JP'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://app:8000');
 assert.equal(await page.locator('.tree-node').count(),11);
 await page.screenshot({path:'/work/qa/desktop.png',fullPage:true});
 await page.getByRole('button',{name:'佐藤 健一を編集',exact:true}).click();
 await page.locator('[name="name"]').fill('佐藤 健一郎');
 await page.getByRole('button',{name:'保存する',exact:true}).click();
 await page.reload();
 assert.equal(await page.getByRole('button',{name:'佐藤 健一郎を編集',exact:true}).count(),1);
 await page.getByRole('button',{name:'＋ 人物を追加',exact:true}).click();
 await page.locator('[name="name"]').fill('佐藤 葵');
 await page.locator('[name="kind"]').selectOption('grandchild');
 await page.locator('[name="birth"]').fill('2005-01-02');
 await page.getByRole('button',{name:'保存する',exact:true}).click();
 assert.equal(await page.locator('.tree-node').count(),12);
 await page.getByRole('tab',{name:'人物情報',exact:true}).click();
 await page.getByRole('checkbox',{name:'佐藤 葵を出力対象にする'}).check();
 await page.getByRole('tab',{name:'一覧図プレビューA4'}).click();
 assert.equal(await page.locator('#print-document').isDisabled(),true);
 assert.match(await page.locator('#document-errors').innerText(),/未対応の続柄/);
 await page.getByRole('tab',{name:'家系図',exact:true}).click();
 await page.getByRole('button',{name:'佐藤 葵を編集',exact:true}).click();
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'削除',exact:true}).click();
 assert.equal(await page.locator('.tree-node').count(),11);
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'サンプルに戻す',exact:true}).click();
 await page.getByRole('tab',{name:'一覧図プレビューA4'}).click();
 assert.equal(await page.locator('#print-document').isDisabled(),false);
 await page.locator('#include-address').check();
 await page.screenshot({path:'/work/qa/document.png',fullPage:true});
 await page.emulateMedia({media:'print'});
 await page.screenshot({path:'/work/qa/print.png',fullPage:true});
 const boxes=await page.evaluate(()=>({creator:document.querySelector('.legal-creator').getBoundingClientRect().bottom,note:document.querySelector('.paper-note').getBoundingClientRect().top,height:document.documentElement.scrollHeight}));
 assert.ok(boxes.creator<boxes.note,JSON.stringify(boxes));
 await page.emulateMedia({media:'screen'});
 const download=page.waitForEvent('download');await page.locator('#backup').click();const file=await download;await file.saveAs('/work/qa/backup.json');
 page.once('dialog',d=>d.accept());await page.locator('#import-file').setInputFiles('/work/qa/backup.json');await page.waitForTimeout(150);
 assert.equal(await page.locator('#person-count').innerText(),'11');
 await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":1,"people":[]}')});
 await page.waitForTimeout(150);assert.match(await page.locator('#toast').innerText(),/読み込めません/);
 await page.getByRole('tab',{name:'家系図',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/work/qa/mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);
 await browser.close();console.log('PASS: editing, persistence, add/delete, unsupported export guard, print layout, JSON export/import, invalid import, mobile overflow, no browser errors.');
})().catch(e=>{console.error(e);process.exit(1)});
