# Generated by Django 6.0.1 on 2026-01-25 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='案件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件一覧',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='取引日')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='摘要')),
                ('amount_out', models.IntegerField(default=0, verbose_name='出金')),
                ('amount_in', models.IntegerField(default=0, verbose_name='入金')),
                ('balance', models.IntegerField(blank=True, null=True, verbose_name='残高')),
                ('account_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='口座ID')),
                ('holder', models.CharField(blank=True, max_length=255, null=True, verbose_name='名義人')),
                ('is_large', models.BooleanField(default=False, verbose_name='多額取引')),
                ('is_transfer', models.BooleanField(default=False, verbose_name='資金移動')),
                ('transfer_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='移動先推定')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='分類')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='analyzer.case', verbose_name='案件')),
            ],
            options={
                'verbose_name': '取引',
                'verbose_name_plural': '取引一覧',
            },
        ),
    ]
