# Generated by Django 6.0.1 on 2026-01-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='銀行名'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='支店名'),
        ),
    ]
