# Generated by Django 6.0.1 on 2026-01-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_transaction_bank_name_transaction_branch_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'verbose_name': '案件', 'verbose_name_plural': '案件一覧'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date', 'id'], 'verbose_name': '取引', 'verbose_name_plural': '取引一覧'},
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['case', 'date'], name='analyzer_tr_case_id_ff6ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['case', 'account_id'], name='analyzer_tr_case_id_cfc7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='analyzer_tr_categor_07dd04_idx'),
        ),
    ]
