# Generated by Django 6.0.1 on 2026-01-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_add_flagged_and_memo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='analyzer_tr_case_id_ca6c16_idx',
            old_name='analyzer_tr_case_id_flagged_idx',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='種別'),
        ),
    ]
