# Generated by Django 6.0.2 on 2026-02-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_add_account_type'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['case', 'category'], name='analyzer_tr_case_id_96ba3a_idx'),
        ),
    ]
